[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
hedgehouse = "J75RtYgFYkCk3wMbGwGrBSZVc8x3CeHFoKRnLBuoCNvi"

[programs.devnet]
hedgehouse = "J75RtYgFYkCk3wMbGwGrBSZVc8x3CeHFoKRnLBuoCNvi"

[programs.mainnet]
hedgehouse = "J75RtYgFYkCk3wMbGwGrBSZVc8x3CeHFoKRnLBuoCNvi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node --experimental-strip-types tests/anchor/hedgehouse.ts"
