import { MarketItem } from './types';
import { getChartObservations, getRegionVerification } from './cache';

export function getMarketsData(): MarketItem[] {
  const miamiVerif = getRegionVerification('miami');
  const londonVerif = getRegionVerification('london');
  const singaporeVerif = getRegionVerification('singapore');
  const sydneyVerif = getRegionVerification('sydney');

  return [
    {
      id: 'miami-fhfa-2027q2-decline',
      ticker: 'MIA-27Q2-DECLINE',
      title: 'Will Miami HPI decline YoY by Q2 2027?',
      city: 'Miami',
      country: 'United States',
      countryCode: 'US',
      coordinates: '25.7617° N, 80.1918° W',
      provider: 'FHFA',
      providerFullName: 'Federal Housing Finance Agency',
      seriesName: 'Miami-Miami Beach-Kendall, FL (MSAD 33124) All-Transactions HPI',
      frequency: 'quarterly',
      baselinePeriod: miamiVerif?.latestPeriod || '2026-Q2',
      baselineValue: miamiVerif?.latestValue || 666.21,
      targetPeriod: '2027-Q2',
      condition: 'TARGET_LT_BASELINE',
      ruleFormula: 'FHFA(2027-Q2) < FHFA(2026-Q2)',
      unit: 'Index Points (Base 100)',
      status: 'DEVNET ACTIVE',
      resolutionDate: 'August 2027',
      officialSourceUrl: 'https://www.fhfa.gov/data/hpi',
      verificationStatus: 'PASS',
      description: 'Resolves against the official FHFA All-Transactions House Price Index for the Miami metropolitan division (MSAD 33124). Evaluates whether 2027-Q2 settles below the confirmed 2026-Q2 baseline.',
      economicContext: 'Miami experienced historic valuation appreciation driven by corporate relocation and climate inflows. Emerging insurance cost pressures, condo association reserve mandates, and mortgage rates represent macro headwinds tested by this contract.',
      historicalSeries: getChartObservations('miami', 14),
    },
    {
      id: 'london-ukhpi-202707-growth',
      ticker: 'LDN-27M07-GROWTH',
      title: 'Will London HPI show positive YoY growth by July 2027?',
      city: 'London',
      country: 'United Kingdom',
      countryCode: 'GB',
      coordinates: '51.5074° N, 0.1278° W',
      provider: 'UKHPI',
      providerFullName: 'HM Land Registry / Office for National Statistics',
      seriesName: 'London Government Office Region (E12000007) Monthly HPI',
      frequency: 'monthly',
      baselinePeriod: londonVerif?.latestPeriod || '2026-07',
      baselineValue: londonVerif?.latestValue || 96.4,
      targetPeriod: '2027-07',
      targetThreshold: 0.0,
      condition: 'YOY_CHANGE_GT',
      ruleFormula: 'UKHPI(2027-07) > UKHPI(2026-07)',
      unit: 'Index Points (Base Jan 2015 = 100)',
      status: 'COMING ON-CHAIN',
      resolutionDate: 'September 2027',
      officialSourceUrl: 'https://landregistry.data.gov.uk',
      verificationStatus: 'PASS',
      description: 'Resolves to YES if the official monthly UK HPI for Greater London published by HM Land Registry reflects strictly positive annual growth (>0.00%) compared to July 2026.',
      economicContext: 'London property valuations balance high mortgage rates with persistent structural undersupply. This contract isolates capital appreciation across all 33 London boroughs.',
      historicalSeries: getChartObservations('london', 12),
    },
    {
      id: 'singapore-ura-2027q2-rise-2pct',
      ticker: 'SG-27Q2-RISE-2PCT',
      title: 'Will Singapore private residential prices rise more than 2% YoY by Q2 2027?',
      city: 'Singapore',
      country: 'Singapore',
      countryCode: 'SG',
      coordinates: '1.3521° N, 103.8198° E',
      provider: 'URA',
      providerFullName: 'Urban Redevelopment Authority',
      seriesName: 'Private Residential Property Price Index (All Types)',
      frequency: 'quarterly',
      baselinePeriod: singaporeVerif?.latestPeriod || '2026-Q2',
      baselineValue: singaporeVerif?.latestValue || 219.4,
      targetPeriod: '2027-Q2',
      targetThreshold: 2.0,
      condition: 'YOY_CHANGE_GT',
      ruleFormula: '((URA(2027-Q2) - URA(2026-Q2)) / URA(2026-Q2)) * 100 > 2.0%',
      unit: 'Index Points (Base 2009-Q1 = 100)',
      status: 'COMING ON-CHAIN',
      resolutionDate: 'July 2027',
      officialSourceUrl: 'https://data.gov.sg/datasets/d_61c02ffae8bb3e85bc9deba04e9e0481',
      verificationStatus: 'PASS',
      description: 'Resolves to YES if the official URA Private Residential Property Price Index published by SingStat via data.gov.sg registers YoY growth exceeding +2.00% by Q2 2027.',
      economicContext: 'Singapore property cooling measures and high stamp duties on foreign buyers face counter-pressure from substantial resident liquidity and rising domestic household incomes.',
      historicalSeries: getChartObservations('singapore', 14),
    },
    {
      id: 'sydney-abs-2027q2-exceed-1500k',
      ticker: 'SYD-27Q2-EXCEED-1500K',
      title: 'Will Sydney established-house median price exceed A$1.5M by Q2 2027?',
      city: 'Sydney',
      country: 'Australia',
      countryCode: 'AU',
      coordinates: '33.8688° S, 151.2093° E',
      provider: 'ABS',
      providerFullName: 'Australian Bureau of Statistics',
      seriesName: 'Cat 6432.0 Total Value of Dwellings — Greater Sydney Median House Price',
      frequency: 'quarterly',
      baselinePeriod: sydneyVerif?.latestPeriod || '2026-Q2',
      baselineValue: sydneyVerif?.latestValue || 1487600,
      targetPeriod: '2027-Q2',
      targetThreshold: 1500000,
      condition: 'TARGET_GT_BASELINE',
      ruleFormula: 'ABS_MEDIAN(2027-Q2) > 1,500,000 AUD',
      unit: 'AUD (Australian Dollars)',
      status: 'COMING ON-CHAIN',
      resolutionDate: 'September 2027',
      officialSourceUrl: 'https://api.data.abs.gov.au',
      verificationStatus: 'PASS',
      description: 'Resolves to YES if the official ABS Cat 6432.0 median sale price for established houses in Greater Sydney reports strictly greater than A$1,500,000 in Q2 2027.',
      economicContext: 'Sydney home prices trade near record valuations. Strong immigration intake and construction capacity limitations compete directly against borrowing capacity limits.',
      historicalSeries: getChartObservations('sydney', 12),
    },
  ];
}

export const MARKETS_DATA = getMarketsData();

export function getMarketById(id: string): MarketItem | undefined {
  return getMarketsData().find((m) => m.id === id);
}
