import { ProviderProfile } from './types';

export const OFFICIAL_PROVIDERS: ProviderProfile[] = [
  {
    id: 'FHFA',
    name: 'Federal Housing Finance Agency',
    country: 'United States',
    countryCode: 'US',
    jurisdiction: 'Federal Government of the United States',
    frequency: 'quarterly',
    publicationLag: 'T + 60 days (Late February, May, August, November)',
    latestPeriod: '2026-Q2',
    latestValue: '666.21 pts',
    status: 'ONLINE',
    datasetName: 'HPI Master CSV — All-Transactions MSA Index',
    endpoint: 'https://www.fhfa.gov/DataTools/Downloads/Documents/HPI/HPI_master.csv',
    accessMethod: 'Direct HTTP Stream (Automated CSV parsing of MSAD 33124)',
    license: 'Public Domain (US Federal Government Work)',
    description: 'The FHFA House Price Index is a comprehensive collection of public-use single-family house price measures. It evaluates home price changes in hundreds of metropolitan areas using repeat sales data from Fannie Mae and Freddie Mac mortgages.',
    historicalDepth: '1975-Q1 to Present (50+ years of uninterrupted records)',
  },
  {
    id: 'UKHPI',
    name: 'HM Land Registry & ONS',
    country: 'United Kingdom',
    countryCode: 'GB',
    jurisdiction: 'United Kingdom (England & Wales)',
    frequency: 'monthly',
    publicationLag: 'T + 45 days (Third Wednesday of each calendar month)',
    latestPeriod: '2026-07',
    latestValue: '96.4 pts (£550,037 avg)',
    status: 'ONLINE',
    datasetName: 'UK House Price Index Linked Data API',
    endpoint: 'https://landregistry.data.gov.uk/data/hpi/resources',
    accessMethod: 'SPARQL Linked Open Data & REST JSON API',
    license: 'Open Government Licence v3.0 (Crown Copyright)',
    description: 'Calculated by the Office for National Statistics (ONS) using complete registered sales records from HM Land Registry, Registers of Scotland, and Land & Property Services Northern Ireland. Hedonic regression methodology standardizes property characteristics.',
    historicalDepth: 'January 1995 to Present (Complete monthly indices for all London boroughs)',
  },
  {
    id: 'URA',
    name: 'Urban Redevelopment Authority',
    country: 'Singapore',
    countryCode: 'SG',
    jurisdiction: 'Statutory Board under the Ministry of National Development',
    frequency: 'quarterly',
    publicationLag: 'T + 26 days (Flash estimate at T + 1 day; Final on 4th Friday)',
    latestPeriod: '2026-Q2',
    latestValue: '219.4 pts',
    status: 'ONLINE',
    datasetName: 'URA Private Residential Property Price Index',
    endpoint: 'https://data.gov.sg/api/action/datastore_search (Resource: d_61c02ffae8bb3e85bc9deba04e9e0481)',
    accessMethod: 'data.gov.sg CKAN / S3 JSON Stream',
    license: 'Singapore Open Data Licence',
    description: 'The official benchmark for private residential property price movements in the Republic of Singapore. Stratified median price approach covers Core Central Region (CCR), Rest of Central Region (RCR), and Outside Central Region (OCR).',
    historicalDepth: '1975-Q1 to Present (Over 206 quarterly observations cataloged)',
  },
  {
    id: 'ABS',
    name: 'Australian Bureau of Statistics',
    country: 'Australia',
    countryCode: 'AU',
    jurisdiction: 'Commonwealth Government of Australia',
    frequency: 'quarterly',
    publicationLag: 'T + 75 days (Mid-March, June, September, December)',
    latestPeriod: '2026-Q2',
    latestValue: 'A$1,487,600 (Median House)',
    status: 'ONLINE',
    datasetName: 'Cat 6432.0 Total Value of Dwellings (replaces 6416.0)',
    endpoint: 'https://api.data.abs.gov.au/data/ABS,TOTAL_VALUE_DWELLINGS,1.0.0',
    accessMethod: 'SDMX 2.1 REST XML/JSON API',
    license: 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
    description: 'Australia’s national statistical agency tracks total value and median sale prices of residential dwellings across all Greater Capital City Statistical Areas (GCCSA), powered by complete valuer-general registry inputs.',
    historicalDepth: '2021-Q3 to Present (Cat 6432.0 continuous operational series)',
  },
];
